name: CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4.1.1
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./kube-news/src/
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            edgardosreis12/kubenews:${{ github.run_number }}
            edgardosreis12/kubenews:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4.1.1
      - name: Configuração da credencial AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configurar o Kubeconfig
        run: aws eks update-kubeconfig --name imersao_eks --region: us-east-1
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./kube-news/k8s/deployment.yaml
          images: |
            edgardosreis12/kubenews:${{ github.run_number }}










        
