name: CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositório
        uses: actions/checkout@v4.1.1
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./kube-news/src/
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            edgardosreis12/kubenews:${{ github.run_number }}
            edgardosreis12/kubenews:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Autenticar na AWS
        run: echo "Autenticar na AWS"
      - name: Configurar o Kubeconfig
        run: echo "Configurar o Kubeconfig"
      - name: Aplicar o apply
        run: echo "Executar o kubectl apply"
