name: CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Construir a imagem de container
        run: docker build -t $DOCKER_IMAGE .
      - name: Efetuar o login no Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Enviar a imagem para o Docker Registry
        run: docker push minha-imagem

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar na AWS
        run: echo "Autenticar na AWS"
      - name: Configurar o Kubeconfig
        run: echo "Configurar o Kubeconfig"
      - name: Aplicar o apply
        run: kubectl apply -f meu-arquivo.yaml
